[package]
name = "aoc_2019"
version = "0.1.0"
authors = ["Xavier Filippi <filippi.xavier@yahoo.fr>"]
edition = "2018"

[dependencies]
regex = "^1.3.1"
itertools = "^0.8.2"
num-bigint = "0.2.6"
num-traits = "0.2.11"
